FROM datadog/agent:7

ENV DD_APM_ENABLED=true
ENV NON_LOCAL_TRAFFIC=true
ENV DD_APM_NON_LOCAL_TRAFFIC=true
ENV DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
ENV DD_AGENT_MAJOR_VERSION=7
ENV DD_AGENT_MINOR_VERSION=39
ENV DD_HOSTNAME=us5.datadoghq.com

ARG DD_API_KEY
